/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppleIcon: typeof import('./components/Icons/AppleIcon.vue')['default']
    BreadcrumbDefault: typeof import('./components/Breadcrumbs/BreadcrumbDefault.vue')['default']
    DarkModeSwitcher: typeof import('./components/Header/DarkModeSwitcher.vue')['default']
    DropdownMessage: typeof import('./components/Header/DropdownMessage.vue')['default']
    DropdownNotification: typeof import('./components/Header/DropdownNotification.vue')['default']
    DropdownUser: typeof import('./components/Header/DropdownUser.vue')['default']
    ElAlert: typeof import('element-plus/es')['ElAlert']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCheckboxGroup: typeof import('element-plus/es')['ElCheckboxGroup']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElLink: typeof import('element-plus/es')['ElLink']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    FacebookIcon: typeof import('./components/Icons/FacebookIcon.vue')['default']
    GoogleIcon: typeof import('./components/Icons/GoogleIcon.vue')['default']
    HeaderArea: typeof import('./components/Header/HeaderArea.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SidebarArea: typeof import('./components/Sidebar/SidebarArea.vue')['default']
    SidebarDropdown: typeof import('./components/Sidebar/SidebarDropdown.vue')['default']
    SidebarItem: typeof import('./components/Sidebar/SidebarItem.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
